const productPage = {
  "status": 200,
  "message": null,
  "pager": {
    "records_per_page": 10,
    "total_record_count": 85,
    "current_page_record_count": 10,
    "is_first_page": true,
    "is_final_page": false,
    "current_page": 1,
    "current_page_path": "/products?access_key=MDo3MmM2MDczOC05ZmFhLTExZTYtOWExYS1kYjhlYzc1N2RmMmE6Y0J3VUM1eDlhWFFwUVNWMDdFUUQ4YmdxV2pNOUJFMUpOOUEw&per_page=10&q=cider&xmlToJSON=false&page=1",
    "next_page": 2,
    "next_page_path": "/products?access_key=MDo3MmM2MDczOC05ZmFhLTExZTYtOWExYS1kYjhlYzc1N2RmMmE6Y0J3VUM1eDlhWFFwUVNWMDdFUUQ4YmdxV2pNOUJFMUpOOUEw&per_page=10&q=cider&xmlToJSON=false&page=2",
    "previous_page": null,
    "previous_page_path": null,
    "total_pages": 9,
    "total_pages_path": "/products?access_key=MDo3MmM2MDczOC05ZmFhLTExZTYtOWExYS1kYjhlYzc1N2RmMmE6Y0J3VUM1eDlhWFFwUVNWMDdFUUQ4YmdxV2pNOUJFMUpOOUEw&per_page=10&q=cider&xmlToJSON=false&page=9"
  },
  "result": [
    {
      "id": 279307,
      "is_dead": false,
      "name": "Somersby Apple Cider",
      "tags": "somersby apple cider ciders denmark region not specified carlsberg canada inc can",
      "is_discontinued": false,
      "price_in_cents": 290,
      "regular_price_in_cents": 310,
      "limited_time_offer_savings_in_cents": 20,
      "limited_time_offer_ends_on": "2017-01-29",
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Denmark, Region Not Specified",
      "package": "500 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 500,
      "total_package_units": 1,
      "volume_in_milliliters": 500,
      "alcohol_content": 450,
      "price_per_liter_of_alcohol_in_cents": 1288,
      "price_per_liter_in_cents": 580,
      "inventory_count": 86028,
      "inventory_volume_in_milliliters": 43014000,
      "inventory_price_in_cents": 24948120,
      "sugar_content": null,
      "producer_name": "Carlsberg Canada Inc.",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": true,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:33:34.784Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/279307/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/279307/images/full.jpeg",
      "varietal": null,
      "style": "Sweet & Fruity",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": null,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 279307
    },
    {
      "id": 560532,
      "is_dead": false,
      "name": "Strongbow Cider",
      "tags": "strongbow cider ciders united kingdom region not specified scottish newcastle breweries ltd can",
      "is_discontinued": false,
      "price_in_cents": 310,
      "regular_price_in_cents": 310,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "United Kingdom, Region Not Specified",
      "package": "500 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 500,
      "total_package_units": 1,
      "volume_in_milliliters": 500,
      "alcohol_content": 530,
      "price_per_liter_of_alcohol_in_cents": 1169,
      "price_per_liter_in_cents": 620,
      "inventory_count": 82712,
      "inventory_volume_in_milliliters": 41356000,
      "inventory_price_in_cents": 25640720,
      "sugar_content": null,
      "producer_name": "Scottish & Newcastle Breweries Ltd.",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:34:06.812Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/560532/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/560532/images/full.jpeg",
      "varietal": null,
      "style": "Dry & Crisp",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": 30,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 560532
    },
    {
      "id": 394015,
      "is_dead": false,
      "name": "Brickworks Ciderhouse Batch : 1904",
      "tags": "brickworks ciderhouse batch : 1904 ciders cider canada ontario can",
      "is_discontinued": false,
      "price_in_cents": 315,
      "regular_price_in_cents": 315,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Canada, Ontario",
      "package": "473 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 473,
      "total_package_units": 1,
      "volume_in_milliliters": 473,
      "alcohol_content": 470,
      "price_per_liter_of_alcohol_in_cents": 1416,
      "price_per_liter_in_cents": 665,
      "inventory_count": 47150,
      "inventory_volume_in_milliliters": 22301950,
      "inventory_price_in_cents": 14852250,
      "sugar_content": null,
      "producer_name": "Brickworks Ciderhouse",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:18:24.797Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/394015/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/394015/images/full.jpeg",
      "varietal": null,
      "style": "Dry & Aromatic",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": 28,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 394015
    },
    {
      "id": 331348,
      "is_dead": false,
      "name": "Somersby Blackberry Cider",
      "tags": "somersby blackberry cider ciders denmark region not specified carlsberg canada inc can",
      "is_discontinued": false,
      "price_in_cents": 310,
      "regular_price_in_cents": 310,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Denmark, Region Not Specified",
      "package": "500 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 500,
      "total_package_units": 1,
      "volume_in_milliliters": 500,
      "alcohol_content": 450,
      "price_per_liter_of_alcohol_in_cents": 1377,
      "price_per_liter_in_cents": 620,
      "inventory_count": 44378,
      "inventory_volume_in_milliliters": 22189000,
      "inventory_price_in_cents": 13757180,
      "sugar_content": null,
      "producer_name": "Carlsberg Canada Inc.",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:33:35.000Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/331348/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/331348/images/full.jpeg",
      "varietal": null,
      "style": "Sweet & Fruity",
      "tertiary_category": "Flavoured Cider",
      "sugar_in_grams_per_liter": 78,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 331348
    },
    {
      "id": 413807,
      "is_dead": false,
      "name": "Brickworks Ciderhouse Queen Street 501",
      "tags": "brickworks ciderhouse queen street 501 ciders cider canada ontario can",
      "is_discontinued": false,
      "price_in_cents": 300,
      "regular_price_in_cents": 300,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Canada, Ontario",
      "package": "473 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 473,
      "total_package_units": 1,
      "volume_in_milliliters": 473,
      "alcohol_content": 500,
      "price_per_liter_of_alcohol_in_cents": 1268,
      "price_per_liter_in_cents": 634,
      "inventory_count": 30324,
      "inventory_volume_in_milliliters": 14343252,
      "inventory_price_in_cents": 9097200,
      "sugar_content": null,
      "producer_name": "Brickworks Ciderhouse",
      "released_on": "2015-10-26",
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": "Serve as a crisp aperitif, with patio and pub fare or a selection of local cheeses.",
      "tasting_note": "Clear pale gold in colour, with a long-lasting head of lacy foam; medium-plus intensity of aroma, with notes of ripe and lightly bruised apple; on the palate, clean, crisp and mildly sweet, with medium body and fine-textured carbonation; flavours of binned apple, white blossoms and honey.",
      "updated_at": "2017-01-05T14:18:24.899Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/413807/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/413807/images/full.jpeg",
      "varietal": null,
      "style": "Medium-Sweet & Aromatic",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": null,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 413807
    },
    {
      "id": 413138,
      "is_dead": false,
      "name": "Somersby Pear Cider",
      "tags": "somersby pear cider ciders denmark region not specified carlsberg canada inc can",
      "is_discontinued": false,
      "price_in_cents": 310,
      "regular_price_in_cents": 310,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Denmark, Region Not Specified",
      "package": "500 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 500,
      "total_package_units": 1,
      "volume_in_milliliters": 500,
      "alcohol_content": 450,
      "price_per_liter_of_alcohol_in_cents": 1377,
      "price_per_liter_in_cents": 620,
      "inventory_count": 25245,
      "inventory_volume_in_milliliters": 12622500,
      "inventory_price_in_cents": 7825950,
      "sugar_content": null,
      "producer_name": "Carlsberg Canada Inc.",
      "released_on": "2016-04-18",
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": "Refreshing on its own or pair with spicy Indian curries.",
      "tasting_note": "This popular pear cider is light and refreshing; on the nose you will find aromas of pear, green apple and lime with similar flavours on the medium-sweet palate.",
      "updated_at": "2017-01-05T14:33:35.326Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/413138/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/413138/images/full.jpeg",
      "varietal": null,
      "style": "Medium-Sweet & Fruity",
      "tertiary_category": "Flavoured Cider",
      "sugar_in_grams_per_liter": null,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 413138
    },
    {
      "id": 184796,
      "is_dead": false,
      "name": "Strongbow Cider",
      "tags": "strongbow cider ciders united kingdom england scottish newcastle breweries ltd can",
      "is_discontinued": false,
      "price_in_cents": 2120,
      "regular_price_in_cents": 2120,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "United Kingdom, England",
      "package": "8x440 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 440,
      "total_package_units": 8,
      "volume_in_milliliters": 3520,
      "alcohol_content": 530,
      "price_per_liter_of_alcohol_in_cents": 1136,
      "price_per_liter_in_cents": 602,
      "inventory_count": 3246,
      "inventory_volume_in_milliliters": 11425920,
      "inventory_price_in_cents": 6881520,
      "sugar_content": null,
      "producer_name": "Scottish & Newcastle Breweries Ltd.",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:34:07.045Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/184796/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/184796/images/full.jpeg",
      "varietal": null,
      "style": "Dry & Crisp",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": 30,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 184796
    },
    {
      "id": 699389,
      "is_dead": false,
      "name": "Magners Original Irish Cider",
      "tags": "magners original irish cider ciders ireland region not specified william magner co can",
      "is_discontinued": false,
      "price_in_cents": 310,
      "regular_price_in_cents": 310,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Ireland, Region Not Specified",
      "package": "500 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 500,
      "total_package_units": 1,
      "volume_in_milliliters": 500,
      "alcohol_content": 450,
      "price_per_liter_of_alcohol_in_cents": 1377,
      "price_per_liter_in_cents": 620,
      "inventory_count": 22565,
      "inventory_volume_in_milliliters": 11282500,
      "inventory_price_in_cents": 6995150,
      "sugar_content": null,
      "producer_name": "William Magner & Co",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:28:17.057Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/699389/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/699389/images/full.jpeg",
      "varietal": null,
      "style": "Medium-Sweet & Rustic",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": 38,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 699389
    },
    {
      "id": 339770,
      "is_dead": false,
      "name": "Molson Canadian Cider",
      "tags": "molson canadian cider ciders canada ontario molson's molsons brewery can",
      "is_discontinued": false,
      "price_in_cents": 300,
      "regular_price_in_cents": 300,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Canada, Ontario",
      "package": "473 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 473,
      "total_package_units": 1,
      "volume_in_milliliters": 473,
      "alcohol_content": 500,
      "price_per_liter_of_alcohol_in_cents": 1268,
      "price_per_liter_in_cents": 634,
      "inventory_count": 19584,
      "inventory_volume_in_milliliters": 9263232,
      "inventory_price_in_cents": 5875200,
      "sugar_content": null,
      "producer_name": "Molson's Brewery Cider",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:29:20.495Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/339770/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/339770/images/full.jpeg",
      "varietal": null,
      "style": "Medium-Sweet & Fruity",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": null,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 339770
    },
    {
      "id": 391862,
      "is_dead": false,
      "name": "Okanagan Premium Dry Cider",
      "tags": "okanagan premium dry cider ciders canada british columbia great west distillers can",
      "is_discontinued": false,
      "price_in_cents": 280,
      "regular_price_in_cents": 280,
      "limited_time_offer_savings_in_cents": 0,
      "limited_time_offer_ends_on": null,
      "bonus_reward_miles": 0,
      "bonus_reward_miles_ends_on": null,
      "stock_type": "LCBO",
      "primary_category": "Ciders",
      "secondary_category": "Cider",
      "origin": "Canada, British Columbia",
      "package": "473 mL can",
      "package_unit_type": "can",
      "package_unit_volume_in_milliliters": 473,
      "total_package_units": 1,
      "volume_in_milliliters": 473,
      "alcohol_content": 500,
      "price_per_liter_of_alcohol_in_cents": 1183,
      "price_per_liter_in_cents": 591,
      "inventory_count": 19448,
      "inventory_volume_in_milliliters": 9198904,
      "inventory_price_in_cents": 5445440,
      "sugar_content": null,
      "producer_name": "Great West Distillers",
      "released_on": null,
      "has_value_added_promotion": false,
      "has_limited_time_offer": false,
      "has_bonus_reward_miles": false,
      "is_seasonal": false,
      "is_vqa": false,
      "is_ocb": false,
      "is_kosher": false,
      "value_added_promotion_description": null,
      "description": null,
      "serving_suggestion": null,
      "tasting_note": null,
      "updated_at": "2017-01-05T14:30:06.275Z",
      "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/391862/images/thumb.png",
      "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/391862/images/full.jpeg",
      "varietal": null,
      "style": "Dry & Fruity",
      "tertiary_category": "Traditional Cider",
      "sugar_in_grams_per_liter": 54,
      "clearance_sale_savings_in_cents": 0,
      "has_clearance_sale": false,
      "product_no": 391862
    }
  ],
  "suggestion": null
};

const storePage = {
  "status": 200,
  "message": null,
  "pager": {
    "records_per_page": 20,
    "total_record_count": 613,
    "current_page_record_count": 20,
    "is_first_page": true,
    "is_final_page": false,
    "current_page": 1,
    "current_page_path": "/stores?access_key=MDo3MmM2MDczOC05ZmFhLTExZTYtOWExYS1kYjhlYzc1N2RmMmE6Y0J3VUM1eDlhWFFwUVNWMDdFUUQ4YmdxV2pNOUJFMUpOOUEw&geo=100%20Queen%20St%20W,%20Toronto,%20ON&product_id=560532&page=1",
    "next_page": 2,
    "next_page_path": "/stores?access_key=MDo3MmM2MDczOC05ZmFhLTExZTYtOWExYS1kYjhlYzc1N2RmMmE6Y0J3VUM1eDlhWFFwUVNWMDdFUUQ4YmdxV2pNOUJFMUpOOUEw&geo=100%20Queen%20St%20W,%20Toronto,%20ON&product_id=560532&page=2",
    "previous_page": null,
    "previous_page_path": null,
    "total_pages": 31,
    "total_pages_path": "/stores?access_key=MDo3MmM2MDczOC05ZmFhLTExZTYtOWExYS1kYjhlYzc1N2RmMmE6Y0J3VUM1eDlhWFFwUVNWMDdFUUQ4YmdxV2pNOUJFMUpOOUEw&geo=100%20Queen%20St%20W,%20Toronto,%20ON&product_id=560532&page=31"
  },
  "product": {
    "id": 560532,
    "is_dead": false,
    "name": "Strongbow Cider",
    "tags": "strongbow cider ciders united kingdom region not specified scottish newcastle breweries ltd can",
    "is_discontinued": false,
    "price_in_cents": 310,
    "regular_price_in_cents": 310,
    "limited_time_offer_savings_in_cents": 0,
    "limited_time_offer_ends_on": null,
    "bonus_reward_miles": 0,
    "bonus_reward_miles_ends_on": null,
    "stock_type": "LCBO",
    "primary_category": "Ciders",
    "secondary_category": "Cider",
    "origin": "United Kingdom, Region Not Specified",
    "package": "500 mL can",
    "package_unit_type": "can",
    "package_unit_volume_in_milliliters": 500,
    "total_package_units": 1,
    "volume_in_milliliters": 500,
    "alcohol_content": 530,
    "price_per_liter_of_alcohol_in_cents": 1169,
    "price_per_liter_in_cents": 620,
    "inventory_count": 82712,
    "inventory_volume_in_milliliters": 41356000,
    "inventory_price_in_cents": 25640720,
    "sugar_content": null,
    "producer_name": "Scottish & Newcastle Breweries Ltd.",
    "released_on": null,
    "has_value_added_promotion": false,
    "has_limited_time_offer": false,
    "has_bonus_reward_miles": false,
    "is_seasonal": false,
    "is_vqa": false,
    "is_ocb": false,
    "is_kosher": false,
    "value_added_promotion_description": null,
    "description": null,
    "serving_suggestion": null,
    "tasting_note": null,
    "updated_at": "2017-01-05T14:34:06.812Z",
    "image_thumb_url": "https://dx5vpyka4lqst.cloudfront.net/products/560532/images/thumb.png",
    "image_url": "https://dx5vpyka4lqst.cloudfront.net/products/560532/images/full.jpeg",
    "varietal": null,
    "style": "Dry & Crisp",
    "tertiary_category": "Traditional Cider",
    "sugar_in_grams_per_liter": 30,
    "clearance_sale_savings_in_cents": 0,
    "has_clearance_sale": false,
    "product_no": 560532
  },
  "result": [
    {
      "id": 568,
      "is_dead": false,
      "name": "Yonge & Dundas",
      "tags": "yonge dundas 595 bay street lower concourse toronto central toronto-central torontocentral m5g2c2",
      "address_line_1": "595 Bay Street",
      "address_line_2": "Lower Concourse",
      "city": "Toronto",
      "postal_code": "M5G2C2",
      "telephone": "(416) 979-9978",
      "fax": "(416) 979-0988",
      "latitude": 43.6564,
      "longitude": -79.3815,
      "products_count": 2559,
      "inventory_count": 75523,
      "inventory_price_in_cents": 107569281,
      "inventory_volume_in_milliliters": 52146797,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": true,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1320,
      "tuesday_open": 600,
      "tuesday_close": 1320,
      "wednesday_open": 600,
      "wednesday_close": 1320,
      "thursday_open": 600,
      "thursday_close": 1320,
      "friday_open": 600,
      "friday_close": 1320,
      "saturday_open": 600,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:15.095Z",
      "quantity": 507,
      "updated_on": "2017-01-04",
      "distance_in_meters": 376,
      "store_no": 568
    },
    {
      "id": 333,
      "is_dead": false,
      "name": "Bay & King",
      "tags": "bay king 100 street west lower concourse toronto central toronto-central torontocentral m5x1b1",
      "address_line_1": "100 King Street West",
      "address_line_2": "Lower Concourse",
      "city": "Toronto",
      "postal_code": "M5X1B1",
      "telephone": "(416) 594-9040",
      "fax": "(416) 594-6461",
      "latitude": 43.6486,
      "longitude": -79.3822,
      "products_count": 764,
      "inventory_count": 19105,
      "inventory_price_in_cents": 35170697,
      "inventory_volume_in_milliliters": 12530329,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": null,
      "sunday_close": null,
      "monday_open": 600,
      "monday_close": 1080,
      "tuesday_open": 600,
      "tuesday_close": 1080,
      "wednesday_open": 600,
      "wednesday_close": 1080,
      "thursday_open": 600,
      "thursday_close": 1140,
      "friday_open": 600,
      "friday_close": 1140,
      "saturday_open": null,
      "saturday_close": null,
      "updated_at": "2017-01-05T14:15:15.175Z",
      "quantity": 74,
      "updated_on": "2017-01-04",
      "distance_in_meters": 566,
      "store_no": 333
    },
    {
      "id": 646,
      "is_dead": false,
      "name": "College & Bay",
      "tags": "college bay 777 street toronto central toronto-central torontocentral m5g2c8",
      "address_line_1": "777 Bay Street",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5G2C8",
      "telephone": "(416) 593-9076",
      "fax": "(416) 593-5273",
      "latitude": 43.6605,
      "longitude": -79.3846,
      "products_count": 1479,
      "inventory_count": 36370,
      "inventory_price_in_cents": 42766637,
      "inventory_volume_in_milliliters": 24215283,
      "has_wheelchair_accessability": false,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 720,
      "sunday_close": 1020,
      "monday_open": 540,
      "monday_close": 1260,
      "tuesday_open": 540,
      "tuesday_close": 1260,
      "wednesday_open": 540,
      "wednesday_close": 1260,
      "thursday_open": 540,
      "thursday_close": 1260,
      "friday_open": 540,
      "friday_close": 1260,
      "saturday_open": 540,
      "saturday_close": 1080,
      "updated_at": "2017-01-05T14:15:14.741Z",
      "quantity": 132,
      "updated_on": "2017-01-04",
      "distance_in_meters": 781,
      "store_no": 646
    },
    {
      "id": 483,
      "is_dead": false,
      "name": "Front & Bay",
      "tags": "front bay 200 street unit 115 toronto central toronto-central torontocentral m5j2j2",
      "address_line_1": "200 Bay Street, Unit 115",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5J2J2",
      "telephone": "(416) 368-9644",
      "fax": "(416) 368-9711",
      "latitude": 43.6465,
      "longitude": -79.3801,
      "products_count": 1459,
      "inventory_count": 38440,
      "inventory_price_in_cents": 60983375,
      "inventory_volume_in_milliliters": 26498492,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": null,
      "sunday_close": null,
      "monday_open": 540,
      "monday_close": 1200,
      "tuesday_open": 540,
      "tuesday_close": 1200,
      "wednesday_open": 540,
      "wednesday_close": 1200,
      "thursday_open": 540,
      "thursday_close": 1200,
      "friday_open": 540,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1200,
      "updated_at": "2017-01-05T14:15:15.417Z",
      "quantity": 389,
      "updated_on": "2017-01-04",
      "distance_in_meters": 833,
      "store_no": 483
    },
    {
      "id": 614,
      "is_dead": false,
      "name": "Carlton & Church",
      "tags": "carlton church 60 st toronto central toronto-central torontocentral m5b2h5",
      "address_line_1": "60 Carlton St",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5B2H5",
      "telephone": "(416) 599-1967",
      "fax": "(416) 599-1950",
      "latitude": 43.6621,
      "longitude": -79.3803,
      "products_count": 1700,
      "inventory_count": 50742,
      "inventory_price_in_cents": 67921766,
      "inventory_volume_in_milliliters": 37064993,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": false,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 570,
      "monday_close": 1320,
      "tuesday_open": 570,
      "tuesday_close": 1320,
      "wednesday_open": 570,
      "wednesday_close": 1320,
      "thursday_open": 570,
      "thursday_close": 1320,
      "friday_open": 570,
      "friday_close": 1320,
      "saturday_open": 570,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:15.337Z",
      "quantity": 290,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1003,
      "store_no": 614
    },
    {
      "id": 532,
      "is_dead": false,
      "name": "Front St & Jarvis St",
      "tags": "front st jarvis 87 street e lawrence market toronto central toronto-central torontocentral m5b1b8",
      "address_line_1": "87 Front Street E.",
      "address_line_2": "St. Lawrence Market",
      "city": "Toronto",
      "postal_code": "M5B1B8",
      "telephone": "(416) 368-0521",
      "fax": "(416) 368-9153",
      "latitude": 43.6488,
      "longitude": -79.3722,
      "products_count": 2727,
      "inventory_count": 61030,
      "inventory_price_in_cents": 97913111,
      "inventory_volume_in_milliliters": 45865869,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 540,
      "monday_close": 1260,
      "tuesday_open": 540,
      "tuesday_close": 1260,
      "wednesday_open": 540,
      "wednesday_close": 1260,
      "thursday_open": 540,
      "thursday_close": 1260,
      "friday_open": 540,
      "friday_close": 1260,
      "saturday_open": 540,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:15.631Z",
      "quantity": 184,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1079,
      "store_no": 532
    },
    {
      "id": 14,
      "is_dead": false,
      "name": "Spadina & Dundas",
      "tags": "spadina dundas 337 avenue toronto central toronto-central torontocentral m5t2e9",
      "address_line_1": "337 Spadina Avenue",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5T2E9",
      "telephone": "(416) 597-0145",
      "fax": "(416) 597-3851",
      "latitude": 43.6548,
      "longitude": -79.3985,
      "products_count": 1761,
      "inventory_count": 49010,
      "inventory_price_in_cents": 65996158,
      "inventory_volume_in_milliliters": 35844607,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": false,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": true,
      "has_transit_access": true,
      "sunday_open": 720,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1320,
      "saturday_open": 600,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:14.181Z",
      "quantity": 400,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1176,
      "store_no": 14
    },
    {
      "id": 411,
      "is_dead": false,
      "name": "Yonge & Wellesley",
      "tags": "yonge wellesley 547 street toronto central toronto-central torontocentral m4y1y5",
      "address_line_1": "547 Yonge Street",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M4Y1Y5",
      "telephone": "(416) 923-8498",
      "fax": "(416) 923-0659",
      "latitude": 43.6645,
      "longitude": -79.3842,
      "products_count": 2558,
      "inventory_count": 66710,
      "inventory_price_in_cents": 82919028,
      "inventory_volume_in_milliliters": 46792120,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1320,
      "tuesday_open": 600,
      "tuesday_close": 1320,
      "wednesday_open": 600,
      "wednesday_close": 1320,
      "thursday_open": 600,
      "thursday_close": 1320,
      "friday_open": 600,
      "friday_close": 1320,
      "saturday_open": 600,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:14.867Z",
      "quantity": 298,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1220,
      "store_no": 411
    },
    {
      "id": 511,
      "is_dead": false,
      "name": "King & Spadina",
      "tags": "king spadina 415 street west toronto central toronto-central torontocentral m5v1k1",
      "address_line_1": "415 King Street West",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5V1K1",
      "telephone": "(416) 598-1482",
      "fax": "(416) 598-3716",
      "latitude": 43.6453,
      "longitude": -79.3946,
      "products_count": 3096,
      "inventory_count": 83682,
      "inventory_price_in_cents": 139577272,
      "inventory_volume_in_milliliters": 61574193,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": false,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 570,
      "monday_close": 1380,
      "tuesday_open": 570,
      "tuesday_close": 1380,
      "wednesday_open": 570,
      "wednesday_close": 1380,
      "thursday_open": 570,
      "thursday_close": 1380,
      "friday_open": 570,
      "friday_close": 1380,
      "saturday_open": 570,
      "saturday_close": 1380,
      "updated_at": "2017-01-05T14:15:14.483Z",
      "quantity": 70,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1247,
      "store_no": 511
    },
    {
      "id": 677,
      "is_dead": false,
      "name": "York & Lake Shore",
      "tags": "york lake shore 15 street toronto central toronto-central torontocentral m5j0a3",
      "address_line_1": "15 York Street",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5J0A3",
      "telephone": "(416) 594-3838",
      "fax": "(416) 594-6556",
      "latitude": 43.6422,
      "longitude": -79.3808,
      "products_count": 1441,
      "inventory_count": 39950,
      "inventory_price_in_cents": 50336259,
      "inventory_volume_in_milliliters": 27935711,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:15.568Z",
      "quantity": 208,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1278,
      "store_no": 677
    },
    {
      "id": 217,
      "is_dead": false,
      "name": "Queens Quay & Yonge",
      "tags": "queens quay yonge 2 cooper street queen's toronto central toronto-central torontocentral m5e0b8",
      "address_line_1": "2 Cooper Street",
      "address_line_2": "Queen's Quay",
      "city": "Toronto",
      "postal_code": "M5E0B8",
      "telephone": "(416) 864-6777",
      "fax": "(416) 864-6863",
      "latitude": 43.643,
      "longitude": -79.3723,
      "products_count": 4405,
      "inventory_count": 160000,
      "inventory_price_in_cents": 379984699,
      "inventory_volume_in_milliliters": 117054935,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": true,
      "has_vintages_corner": true,
      "has_parking": true,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 540,
      "monday_close": 1320,
      "tuesday_open": 540,
      "tuesday_close": 1320,
      "wednesday_open": 540,
      "wednesday_close": 1320,
      "thursday_open": 540,
      "thursday_close": 1320,
      "friday_open": 540,
      "friday_close": 1320,
      "saturday_open": 540,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:15.769Z",
      "quantity": 662,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1495,
      "store_no": 217
    },
    {
      "id": 656,
      "is_dead": false,
      "name": "Queen & Portland",
      "tags": "queen portland 619 street west toronto central toronto-central torontocentral m5v2b7",
      "address_line_1": "619 Queen Street West",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5V2B7",
      "telephone": "(416) 363-6604",
      "fax": "(416) -       ",
      "latitude": 43.6476,
      "longitude": -79.4015,
      "products_count": 894,
      "inventory_count": 27972,
      "inventory_price_in_cents": 31183436,
      "inventory_volume_in_milliliters": 19247213,
      "has_wheelchair_accessability": false,
      "has_bilingual_services": false,
      "has_product_consultant": false,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": false,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1320,
      "tuesday_open": 600,
      "tuesday_close": 1320,
      "wednesday_open": 600,
      "wednesday_close": 1320,
      "thursday_open": 600,
      "thursday_close": 1320,
      "friday_open": 600,
      "friday_close": 1320,
      "saturday_open": 600,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:14.011Z",
      "quantity": 240,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1556,
      "store_no": 656
    },
    {
      "id": 17,
      "is_dead": false,
      "name": "Front & Sherbourne",
      "tags": "front sherbourne 222 street east toronto central toronto-central torontocentral m5a1e7",
      "address_line_1": "222 Front Street East",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5A1E7",
      "telephone": "(416) 214-0311",
      "fax": "(416) 214-9291",
      "latitude": 43.6512,
      "longitude": -79.3649,
      "products_count": 2795,
      "inventory_count": 56242,
      "inventory_price_in_cents": 92566696,
      "inventory_volume_in_milliliters": 42865839,
      "has_wheelchair_accessability": false,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 720,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1320,
      "friday_open": 600,
      "friday_close": 1320,
      "saturday_open": 600,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:16.065Z",
      "quantity": 102,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1556,
      "store_no": 17
    },
    {
      "id": 528,
      "is_dead": false,
      "name": "Bay & Bloor",
      "tags": "bay bloor 55 street west manulife centre toronto central toronto-central torontocentral m4w1a5",
      "address_line_1": "55 Bloor Street West",
      "address_line_2": "Manulife Centre",
      "city": "Toronto",
      "postal_code": "M4W1A5",
      "telephone": "(416) 925-5266",
      "fax": "(416) 923-9083",
      "latitude": 43.6692,
      "longitude": -79.3881,
      "products_count": 2598,
      "inventory_count": 71577,
      "inventory_price_in_cents": 122522012,
      "inventory_volume_in_milliliters": 51725894,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": true,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": true,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1200,
      "tuesday_open": 600,
      "tuesday_close": 1200,
      "wednesday_open": 600,
      "wednesday_close": 1200,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:14.676Z",
      "quantity": 78,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1777,
      "store_no": 528
    },
    {
      "id": 12,
      "is_dead": false,
      "name": "Parliament & Gerrard",
      "tags": "parliament gerrard 512 street a toronto central toronto-central torontocentral m4x1p4",
      "address_line_1": "512 Parliament Street a",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M4X1P4",
      "telephone": "(416) 923-6966",
      "fax": "(416) 923-5940",
      "latitude": 43.6655,
      "longitude": -79.3687,
      "products_count": 1260,
      "inventory_count": 32015,
      "inventory_price_in_cents": 46800443,
      "inventory_volume_in_milliliters": 23590257,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": false,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": false,
      "has_parking": true,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:15.928Z",
      "quantity": 263,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1820,
      "store_no": 12
    },
    {
      "id": 512,
      "is_dead": false,
      "name": "Yonge & Bloor",
      "tags": "yonge bloor 20 street east shopping concourse level toronto central toronto-central torontocentral m4w3g7",
      "address_line_1": "20 Bloor Street East",
      "address_line_2": "Shopping Concourse Level",
      "city": "Toronto",
      "postal_code": "M4W3G7",
      "telephone": "(416) 925-1434",
      "fax": "(416) 925-1502",
      "latitude": 43.6708,
      "longitude": -79.3859,
      "products_count": 845,
      "inventory_count": 26816,
      "inventory_price_in_cents": 29725460,
      "inventory_volume_in_milliliters": 18645526,
      "has_wheelchair_accessability": false,
      "has_bilingual_services": true,
      "has_product_consultant": false,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": false,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1200,
      "tuesday_open": 600,
      "tuesday_close": 1200,
      "wednesday_open": 600,
      "wednesday_close": 1200,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1080,
      "updated_at": "2017-01-05T14:15:14.933Z",
      "quantity": 352,
      "updated_on": "2017-01-04",
      "distance_in_meters": 1934,
      "store_no": 512
    },
    {
      "id": 639,
      "is_dead": false,
      "name": "College & Bathurst",
      "tags": "college bathurst 549 street toronto central toronto-central torontocentral m6g1a9",
      "address_line_1": "549 College Street",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M6G1A9",
      "telephone": "(416) 922-8711",
      "fax": "(416) 922-8721",
      "latitude": 43.6554,
      "longitude": -79.4118,
      "products_count": 1128,
      "inventory_count": 30527,
      "inventory_price_in_cents": 35939396,
      "inventory_volume_in_milliliters": 20491509,
      "has_wheelchair_accessability": false,
      "has_bilingual_services": true,
      "has_product_consultant": false,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": false,
      "has_parking": false,
      "has_transit_access": false,
      "sunday_open": 720,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:13.649Z",
      "quantity": 178,
      "updated_on": "2017-01-04",
      "distance_in_meters": 2251,
      "store_no": 639
    },
    {
      "id": 15,
      "is_dead": false,
      "name": "Dupont & Spadina",
      "tags": "dupont spadina 232 street toronto central toronto-central torontocentral m5r1v7",
      "address_line_1": "232 Dupont Street",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M5R1V7",
      "telephone": "(416) 922-7066",
      "fax": "(416) 922-8440",
      "latitude": 43.6753,
      "longitude": -79.4057,
      "products_count": 2773,
      "inventory_count": 78730,
      "inventory_price_in_cents": 154961065,
      "inventory_volume_in_milliliters": 60783642,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": true,
      "has_vintages_corner": true,
      "has_parking": true,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 600,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:13.935Z",
      "quantity": 570,
      "updated_on": "2017-01-04",
      "distance_in_meters": 2990,
      "store_no": 15
    },
    {
      "id": 10,
      "is_dead": false,
      "name": "Yonge & Summerhill",
      "tags": "yonge summerhill 10 scrivener square subway toronto central toronto-central torontocentral m4w3y9",
      "address_line_1": "10 Scrivener Square",
      "address_line_2": "Summerhill Subway",
      "city": "Toronto",
      "postal_code": "M4W3Y9",
      "telephone": "(416) 922-0403",
      "fax": "(416) 922-3104",
      "latitude": 43.6809,
      "longitude": -79.3905,
      "products_count": 4778,
      "inventory_count": 142014,
      "inventory_price_in_cents": 393934048,
      "inventory_volume_in_milliliters": 102116420,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": true,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": true,
      "has_vintages_corner": true,
      "has_parking": true,
      "has_transit_access": true,
      "sunday_open": 660,
      "sunday_close": 1080,
      "monday_open": 570,
      "monday_close": 1320,
      "tuesday_open": 570,
      "tuesday_close": 1320,
      "wednesday_open": 570,
      "wednesday_close": 1320,
      "thursday_open": 570,
      "thursday_close": 1320,
      "friday_open": 570,
      "friday_close": 1320,
      "saturday_open": 540,
      "saturday_close": 1320,
      "updated_at": "2017-01-05T14:15:15.007Z",
      "quantity": 532,
      "updated_on": "2017-01-04",
      "distance_in_meters": 3092,
      "store_no": 10
    },
    {
      "id": 3,
      "is_dead": false,
      "name": "Dundas & Dovercourt",
      "tags": "dundas dovercourt 1230 street west toronto central toronto-central torontocentral m6j1x5",
      "address_line_1": "1230 Dundas Street West",
      "address_line_2": null,
      "city": "Toronto",
      "postal_code": "M6J1X5",
      "telephone": "(416) 536-4634",
      "fax": "(416) 536-9493",
      "latitude": 43.6496,
      "longitude": -79.4235,
      "products_count": 1817,
      "inventory_count": 70512,
      "inventory_price_in_cents": 106521803,
      "inventory_volume_in_milliliters": 53120437,
      "has_wheelchair_accessability": true,
      "has_bilingual_services": true,
      "has_product_consultant": false,
      "has_tasting_bar": false,
      "has_beer_cold_room": false,
      "has_special_occasion_permits": false,
      "has_vintages_corner": true,
      "has_parking": true,
      "has_transit_access": true,
      "sunday_open": 720,
      "sunday_close": 1080,
      "monday_open": 600,
      "monday_close": 1260,
      "tuesday_open": 600,
      "tuesday_close": 1260,
      "wednesday_open": 600,
      "wednesday_close": 1260,
      "thursday_open": 600,
      "thursday_close": 1260,
      "friday_open": 600,
      "friday_close": 1260,
      "saturday_open": 570,
      "saturday_close": 1260,
      "updated_at": "2017-01-05T14:15:13.404Z",
      "quantity": 812,
      "updated_on": "2017-01-04",
      "distance_in_meters": 3210,
      "store_no": 3
    }
  ]
};
